### PR TITLE
Update base image

### PR DESCRIPTION
**Pull request by SergioGasquez**
This would make it compatible with the latest `espflash` versions

### CODE REVIEW

**Comment by Vollbrecht** [comment]
TLTR: need python3-venv  installed via apt. 

debian bookworm changed some things regarding handling of virtual env, esp-idf checks if virt-env is installed and try's to install it itself via pip. Installing any python package not in a virt-env is not allowed on bookworm anymore, so it needed to be installed by apt or installed in a virt-env, put pip cant create a virt-env to install virt-env, because virt-env is not installed :D.

**Comment by Vollbrecht** [comment]
If my test finished with the new dockerfiles it would make sense also to use the then new upstream container directly inside the .devcontainer.json. The one difference here currently is that it installes esp-idf globally inside the container. I thought about this a bit if it would  make sense for users that generate a new template, to have an installed idf inside already in a global dir, but this would mean we would currently need two different containers per arch because of support of 4.4.6 and 5.1.1. 

But this would further defeat this container as a base image for no_std. I am currently checking out an minimal image for **no_std all** image and compare it with an **all std** image.  My idea here is to maybe have a **no_std** image that really fits your usecase, and we the changes for std with a COPY img into a std one. Need to play with it a bit.

For this repository we could use our new baseimage in this Dockerfile and Layer the installation of the esp-idf version ontop of it

**Comment by SergioGasquez** [comment]
> For this repository we could use our new baseimage in this Dockerfile and Layer the installation of the esp-idf version ontop of it

The thing is we use a pinned nightly version on this training, to make sure everything is stable

**Comment by Vollbrecht** [comment]
> > For this repository we could use our new baseimage in this Dockerfile and Layer the installation of the esp-idf version ontop of it
> 
> The thing is we use a pinned nightly version on this training, to make sure everything is stable

The training assumes esp32c3 right? if we later produces a stable specialized esp32c3 image, it also would have some pinned nightly version in it, the one used on its publish day right?

**Pull request merged**
